name: Check Code
on: 'push'

jobs:
  test:
    name: Test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.18.0-11.1.pre'
          channel: 'beta'
      - name: Get dependencies
        run: flutter pub get
      - name: Run Tests
        run: flutter test
      - name: Run Analyze
        run: flutter analyze
